# Generated by Django 4.1 on 2022-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='problem_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
